Repository StudioAquatan/Saffron, pull requests merged in 2018-04, with the labels that each got.

#3 init petals
  .gitignore
  petals/.gitignore
  petals/README.md
  petals/package.json
  petals/public/favicon.ico
  petals/public/honoka/README.md
  petals/public/honoka/bootstrap.html
  petals/public/honoka/css/bootstrap.css
  petals/public/honoka/css/bootstrap.min.css
  petals/public/honoka/fonts/glyphicons-halflings-regular.eot
  petals/public/honoka/fonts/glyphicons-halflings-regular.svg
  petals/public/honoka/fonts/glyphicons-halflings-regular.ttf
  petals/public/honoka/fonts/glyphicons-halflings-regular.woff
  petals/public/honoka/fonts/glyphicons-halflings-regular.woff2
  petals/public/honoka/js/bootstrap.js
  petals/public/honoka/js/bootstrap.min.js
  petals/public/index.html
  petals/public/manifest.json
  petals/src/App.css
  petals/src/App.js
  petals/src/App.test.js
  petals/src/index.css
  petals/src/index.js
  petals/src/logo.svg
  petals/src/registerServiceWorker.js
  petals/yarn.lock
Labels: enhancement

#12 Routing
  petals/package.json
  petals/src/App.js
  petals/src/components/TopPage.js
  petals/src/index.js
  petals/yarn.lock
Labels: enhancement

#21 mock server構築
  petals/.babelrc
  petals/mock_server/data.js
  petals/mock_server/index.js
  petals/package.json
  petals/yarn.lock
Labels: enhancement

#22 add gitattribures
  .gitattributes
Labels: enhancement, good first issue

#27 Feature/add course
  calyx/src/calyx/settings.py
  calyx/src/courses/__init__.py
  calyx/src/courses/admin.py
  calyx/src/courses/apps.py
  calyx/src/courses/forms.py
  calyx/src/courses/migrations/0001_initial.py
  calyx/src/courses/migrations/__init__.py
  calyx/src/courses/models.py
  calyx/src/courses/tests.py
  calyx/src/courses/views.py
  calyx/src/labs/__init__.py
  calyx/src/labs/admin.py
  calyx/src/labs/apps.py
  calyx/src/labs/migrations/0001_initial.py
  calyx/src/labs/migrations/__init__.py
  calyx/src/labs/models.py
  calyx/src/labs/tests.py
  calyx/src/labs/views.py
  calyx/src/users/admin.py
  calyx/src/users/migrations/0002_user_course.py
  calyx/src/users/migrations/0003_auto_20180429_1609.py
  calyx/src/users/models.py
  calyx/src/years/__init__.py
  calyx/src/years/admin.py
  calyx/src/years/apps.py
  calyx/src/years/migrations/0001_initial.py
  calyx/src/years/migrations/__init__.py
  calyx/src/years/models.py
  calyx/src/years/tests.py
  calyx/src/years/views.py
Labels: task
