Repository StudioAquatan/Saffron, pull requests merged in 2018-12, with the labels that each got.

#51 Feature/dev scripts
  Makefile
  README.md
  bulb/.gitignore
  calyx/.dockerignore
  calyx/Dockerfile
  calyx/conf/calyx.dev.conf
  calyx/conf/calyx.prod.conf
  calyx/conf/calyx.qa.conf
  calyx/src/.env.sample
  calyx/src/.gitignore
  calyx/src/Pipfile
  calyx/src/calyx/settings.py
  calyx/src/static/admin/css/base.css
  calyx/src/static/admin/css/forms.css
  calyx/src/static/admin/css/responsive.css
  calyx/src/static/admin/css/rtl.css
  calyx/src/static/admin/img/README.txt
  calyx/src/static/admin/img/icon-viewlink.svg
  calyx/src/static/admin/js/SelectFilter2.js
  calyx/src/static/admin/js/actions.js
  calyx/src/static/admin/js/actions.min.js
  calyx/src/static/admin/js/admin/DateTimeShortcuts.js
  calyx/src/static/admin/js/admin/RelatedObjectLookups.js
  calyx/src/static/admin/js/cancel.js
  calyx/src/static/admin/js/collapse.js
  calyx/src/static/admin/js/collapse.min.js
  calyx/src/static/admin/js/core.js
  calyx/src/static/admin/js/inlines.js
  calyx/src/static/admin/js/inlines.min.js
  calyx/src/static/admin/js/prepopulate.js
  calyx/src/static/admin/js/prepopulate.min.js
  calyx/src/static/admin/js/urlify.js
  calyx/src/static/admin/js/vendor/jquery/LICENSE.txt
  calyx/src/static/admin/js/vendor/jquery/jquery.js
  calyx/src/static/admin/js/vendor/jquery/jquery.min.js
  calyx/src/static/admin/js/vendor/select2/LICENSE.md
  calyx/src/static/admin/js/vendor/xregexp/LICENSE.txt
  calyx/src/static/rest_framework/docs/css/base.css
  calyx/src/static/rest_framework/js/default.js
  calyx/src/static/rest_framework_swagger/bundles/app.bundle.css
  calyx/src/static/rest_framework_swagger/bundles/app.bundle.js
  calyx/src/static/rest_framework_swagger/bundles/vendors.bundle.css
  calyx/src/static/rest_framework_swagger/bundles/vendors.bundle.js
  calyx/src/static/rest_framework_swagger/favicon-16x16.png
  calyx/src/static/rest_framework_swagger/favicon-32x32.png
  calyx/src/static/rest_framework_swagger/logo_small.png
  calyx/src/uwsgi.ini
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.qa.yml
  petals/.dockerignore
  petals/Dockerfile
  petals/conf/petals.dev.conf
  petals/conf/petals.prod.conf
  petals/conf/petals.qa.conf
  stigma/.env.sample
Labels: enhancement

#52 Feature/ci
  .circleci/config.yml
  README.md
  calyx/Dockerfile
  calyx/src/.gitignore
  calyx/src/Pipfile.lock
Labels: enhancement

#55 Fix jwt refresh disabled
  calyx/src/.env.sample
  calyx/src/calyx/settings.py
Labels: bug

#50 Auth Form
  .gitignore
  petals/.env.development
  petals/.env.production
  petals/.env.sample
  petals/src/App.tsx
  petals/src/actions/auth.ts
  petals/src/api/auth.test.ts
  petals/src/api/auth.ts
  petals/src/api/users.ts
  petals/src/api/util.test.ts
  petals/src/api/util.ts
  petals/src/components/Header.tsx
  petals/src/components/Login.tsx
  petals/src/components/NotFound.tsx
  petals/src/components/SendMail.tsx
  petals/src/components/Signup.tsx
  petals/src/components/TermsOfService.tsx
  petals/src/index.tsx
  petals/src/lib/api.test.ts
  petals/src/lib/auth.ts
  petals/src/reducers/auth.ts
  petals/tslint.json
Labels: enhancement

#57 Fix to use `--cache-from` option in CI
  .circleci/config.yml
Labels: do not merge, enhancement
