Repository StudioAquatan/Saffron, pull requests merged in 2019-03, with the labels that each got.

#197 Calyx/refactor
  calyx/src/courses/schemas.py
  calyx/src/courses/serializers/course.py
  calyx/src/courses/serializers/course_user.py
  calyx/src/courses/services/__init__.py
  calyx/src/courses/services/config.py
  calyx/src/courses/services/status.py
  calyx/src/courses/services/summary.py
  calyx/src/courses/tests/test_serializers.py
  calyx/src/courses/tests/views/test_course_view.py
  calyx/src/courses/tests/views/test_requirement_status_view.py
  calyx/src/courses/tests/views/test_year_view.py
  calyx/src/courses/views/__init__.py
  calyx/src/courses/views/course_user.py
  calyx/src/courses/views/courses.py
  calyx/src/courses/views/labs.py
  calyx/src/courses/views/mixins.py
  calyx/src/courses/views/ranks.py
  calyx/src/users/serializers.py
Labels: enhancement

#201 NotificationBar
  petals/src/App.tsx
  petals/src/actions/notification.ts
  petals/src/components/Common/GridPaper.tsx
  petals/src/components/NotificationBar.tsx
  petals/src/reducers/__tests__/notification.test.ts
  petals/src/reducers/index.ts
  petals/src/reducers/notification.ts
  petals/src/store/index.ts
Labels: enhancement

#202 Fix GPA in dummy data
  calyx/src/courses/management/commands/create_test_data.py
  calyx/src/courses/signals.py
  calyx/src/dummy.json
Labels: bug

#195 Course list and join
  petals/src/App.tsx
  petals/src/api/index.ts
  petals/src/components/Auth/Signup.tsx
  petals/src/components/Common/GridDialog.tsx
  petals/src/components/Course/CourseList.tsx
  petals/src/components/Course/index.ts
  petals/src/components/Profile.tsx
Labels: enhancement

#211 Fix information showing at admin list
  calyx/src/courses/tests/base.py
  calyx/src/courses/tests/views/test_course_admin_view.py
  calyx/src/courses/views/mixins.py
Labels: bug

#214 課程のエンドポイントを刷新
  calyx/src/courses/serializers/__init__.py
  calyx/src/courses/serializers/course.py
  calyx/src/courses/serializers/course_user.py
  calyx/src/courses/tests/base.py
  calyx/src/courses/tests/test_serializers.py
  calyx/src/courses/tests/views/test_course_view.py
  calyx/src/courses/urls.py
  calyx/src/courses/views/__init__.py
  calyx/src/courses/views/course_user.py
  calyx/src/courses/views/courses.py
Labels: bug, enhancement
